services:
  _defaults:
    autowire: true
    autoconfigure: true

  GrossbergerGeorg\RunScript\Configuration\Loader:
    public: true

  GrossbergerGeorg\RunScript\Runner\ScriptBuilder:
    public: true

  GrossbergerGeorg\RunScript\Runner\ScriptStart:
    public: true

  GrossbergerGeorg\RunScript\Runner\ScriptStatus:
    public: true

  GrossbergerGeorg\RunScript\Toolbar\StartRequestHandler:
    public: true

  GrossbergerGeorg\RunScript\Toolbar\StatusRequestHandler:
    public: true

  GrossbergerGeorg\RunScript\Toolbar\ToolbarItem:
    public: true

  GrossbergerGeorg\RunScript\Toolbar\ViewFactory:
    public: true
