
name: 'Code Style'

on: [ push, pull_request ]

jobs:
  code-style:
    name: Checking Code Style
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: 7.4

      - name: Check code style
        run: |
          make style-check
