
name: 'Test'

on: [ push, pull_request ]

jobs:

  unit-test:
    name: Unit Testing
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php:
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
        typo3:
          - '9.5'
          - '10.4'
          - '11.5'
        exclude:
          - php: '7.2'
            typo3: '11.5'
          - php: '7.3'
            typo3: '11.5'
          - php: '8.0'
            typo3: '9.5'
          - php: '8.0'
            typo3: '10.4'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Test TYPO3 ${{ matrix.typo3 }} on PHP ${{ matrix.php }}
        run: |
          jq 'del(.require)' composer.json | jq 'del(.["require-dev"])' > c.json
          rm -rf composer.lock vendor public composer.json
          mv c.json composer.json
          composer require --ansi -n --no-progress --no-plugins --no-scripts typo3/cms-backend:^${{ matrix.typo3 }} typo3/cms-core:^${{ matrix.typo3 }} typo3/cms-extbase:^${{ matrix.typo3 }} typo3/cms-fluid:^${{ matrix.typo3 }}
          composer require --dev --ansi -n --no-progress phpunit/phpunit mikey179/vfsstream
          php vendor/bin/phpunit -c phpunit.xml.dist
