
name: 'Test'

on: [ push, pull_request ]

jobs:

  unit-test:
    name: Unit Testing
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        php:
          - '7.2'
          - '7.3'
          - '7.4'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: nanasess/setup-php@master
        with:
          php-version: ${{ matrix.php }}

      - name: Test TYPO3 v10
        run: |
          jq 'del(.require)' composer.json | jq 'del(.["require-dev"])' > c.json
          rm -rf composer.lock vendor public composer.json
          mv c.json composer.json
          composer require --ansi -n --no-progress --no-plugins --no-scripts typo3/cms-backend:^10 typo3/cms-fluid:^10
          composer require --dev --ansi -n --no-progress phpunit/phpunit mikey179/vfsstream
          php vendor/bin/phpunit -c phpunit.xml.dist

      - name: Test TYPO3 v11
        if: matrix.php == '7.4'
        run: |
          jq 'del(.require)' composer.json | jq 'del(.["require-dev"])' > c.json
          rm -rf composer.lock vendor public composer.json
          mv c.json composer.json
          composer require --ansi -n --no-progress --no-plugins --no-scripts typo3/cms-backend:^11 typo3/cms-fluid:^11
          composer require --dev --ansi -n --no-progress phpunit/phpunit mikey179/vfsstream
          php vendor/bin/phpunit -c phpunit.xml.dist
